server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ $uri.html =404;
    }

    location /downloads/ {
        default_type application/octet-stream;
        add_header Content-Disposition "attachment";
    }
}
